### ISSUE TITLE
Feature Request: Responsive classes

### ISSUE THREAD

**Issue by ThermScissorpunch** [hawezo/tailwindcss-scroll-snap#3]
I would like to enable scroll snapping on mobile and disable it on desktop.
Normally with TailwindCSS I would do it like this:
`<div class="snap-x md:no-snap">`
The addition of the `md:` to the class will only set the style on that CSS breakpoint. Is it possible to add this to this plugin? I cannot seem to find the classes that should be added for responsive breakpoints.

Thanks a lot for developing this plugin!

**Comment by hawezo** [comment]
Hey, you should be able to add the `responsive` variant. See [here](https://tailwindcss.com/docs/configuration/#variants).

```js
module.exports = {
  variants: {
    scrollSnapType: ['responsive']
  }
}
``` 

I didn't test it, let me know if it works!

**Comment by ThermScissorpunch** [comment]
Yessss it workssss, whoohoo!
Thanks a bunch!

**Comment by kafendt** [comment]
Hey there,

loving the plugin, thanks for making this. I've also been looking for this functionality and took me a while to find this issue. It would be really nice to have this information in the readme :)

**Comment by innocenzi** [comment]
@kafendt Sure, I added that to the `README` so it's clearer now. Thanks for your input. :)
